branches:
  only:
    - master

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.1.1
  - ree

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"

script: "DISPLAY=:99.0 bundle exec rake"
